### ISSUE TITLE
Unhiding OpenBoard leaves Unity panel and menubar visible

### ISSUE THREAD

**Issue by fbarillon** [DIP-SEM/OpenBoard#17]
With OB 1.3rc2 on Ubuntu 14.04, if I unhide the board (ctrl-H) or come back from desktop mode, the Unity panel and menubar stay visible (but non active).
See the screen capture :
![masquer-openboard](https://cloud.githubusercontent.com/assets/18069837/14043909/fb2ef112-f289-11e5-8229-6bfea406739a.png)

**Comment by freeheel3r** [comment]
Thanks, this should be fixed by 8fa01c9.
(This also fixes a related issue on Cinnamon and KDE)
