### ISSUE TITLE
Label not completely visible for new folder (depending on internationalization)

### ISSUE THREAD

**Issue by SamuelLongchamps** [DIP-SEM/OpenBoard#21]
![label_too_long_openboard](https://cloud.githubusercontent.com/assets/5256911/14408475/79ae0bc2-fec4-11e5-9b4d-ce5bcc5a1a3f.png)
# Description
Depending on the language, the label used to ask the user to enter a folder's name in the right panel is not completely shown.

## Reproduction steps
* Be in french internationalization
* Activate desktop view
* Open the right panel if not already
* Go into any object library (one of the folder)
* Click on the new folder button at the bottom of the panel

## Expected result
The label asking the user to enter a name for the folder should be fully readable.

## Actual result
On the french internationalization at least, the label is too long and there it cannot be fully read. The label container should maybe expand to allow two lines in order to display the full text.

While working on this bug, note that the background of the label is white. It should have the same background color as the rest of the dialog box (gray).

# Affecting
OS: Debian 8
Version: 1.3.0-rc2

**Comment by freeheel3r** [comment]
Hey, thanks a lot for all your feedback!

I see you've forked the repo and documented a bunch of issues there -- are those issues you plan on working on yourself?
If you'd like to chat, feel free to add me on skype: craig.f.watson. It would be great to collaborate on these.

**Comment by SamuelLongchamps** [comment]
Oh great, I wanted to contact you, but you had no info on your profile ahah!

I'm working on a Debian-based distro for use in schools as a much simpler alternative to Edubuntu and such. We do not have plans yet to tackle all internal issues logged on the short-term, but OpenBoard will be included in the distro and our current priority is to make the software as easily usable specifically on Debian 8. We're still planning our efforts regarding to OpenBoard, but I can confirm we will do pull requests upstream for any bugfixes we do. It would be great to chat in order to synchronize our development for any "enhancement" tasks. Our goal in forking was not to move away from OpenBoard, but rather to get the Debian 8 related stuff in a separate branch we could have control over.  I'll add you on Skype for sure!
