### ISSUE TITLE
Problème en bureau étendu

### ISSUE THREAD

**Issue by PouvoirLard** [DIP-SEM/OpenBoard#24]
Dans la nouvelle version de OpenBoard, il y a un léger bug au niveau du bureau étendu.  En effet, l'écran secondaire n'est pas couvert entièrement par l'application. Si le format du second écran (beamer) n'est pas le même que celui de l'écran de l'ordinateur, le bureau (ou une fenêtre) est visible. Il sera agréable que l'espace supplémentaire soit blanc.

Encore merci pour la nouvelle mise à jour.

**Comment by freeheel3r** [comment]
Est-ce que vous êtes sur OS X? Si oui le problème est maintenant résolu, et tout devrait bien fonctionner dès la version 1.3.0

**Comment by PouvoirLard** [comment]
Je suis en effet sur OS X.  Je me réjouis que ce petit défaut soit corrigé. Car sur la version 1.3.0-rc.2, le bug existe encore. Merci pour les améliorations déjà apporté. La version 1.3.0-rc.2 me parait beaucoup plus réactive que la précédente.

![capture d ecran 2016-04-12 a 11 45 34](https://cloud.githubusercontent.com/assets/18407754/14456317/9a4ef1c0-00a4-11e6-920b-8eaaf7a0059e.png)

**Comment by freeheel3r** [comment]
Already fixed (d1eefcf5)
